# Site settings
title: Keenan Hye
description: 'Acoustical engineering grad student with a passion for the science and art of music production'
url: 'http://keenanhye.com/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Keenan Hye'
  email: keenan.hye@gmail.com
  # facebook_username: keenanhi
  # github_username:  keenanhye
  linkedin_username:  keenanhye
  music_link: whoisyohannes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
